version: '3.9'
services:
  db:
    image: postgres:16
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: portfolio_api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/portfolio?schema=public
      PORT: 3001
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: sh -c "npm run prisma:migrate && node dist/main.js"
volumes:
  pgdata:

